#!/usr/bin/env bash
# tests/smoke.sh: post-install checks for woow-cf-tunnel on a real host. Exits non-zero on
# any failure. Read-only; never prints secrets (it reports whether cloudflared has a
# --token argument, never a value).
#
#   tests/smoke.sh                        after scripts/install.sh / upgrade.sh
#   EXPECT_CONNS=4 tests/smoke.sh         require full HA (4 edge connections)
#   SMOKE_AUTH_USER=.. SMOKE_AUTH_PASS=.. also log in through the auth proxy
#   SMOKE_PROC=/proc                      where to look for cloudflared processes
set -uo pipefail
ENV_FILE=${ENV_FILE:-$HOME/.config/woow-cf-tunnel/woow-cf-tunnel.env}
QDIR=${QL_QUADLET_DIR:-$HOME/.config/containers/systemd}
UNIT=woow-cf-tunnel.service
CTR=woow-cf-tunnel
EXPECT_CONNS=${EXPECT_CONNS:-1}
fails=0
chk() { if eval "$2"; then echo "ok    $1"; else echo "FAIL  $1"; fails=$((fails + 1)); fi; }

# Values the running container actually has (not secrets).
cenv() { podman inspect -f '{{range .Config.Env}}{{println .}}{{end}}' "$CTR" 2>/dev/null | sed -n "s/^$1=//p"; }
PORT=$(cenv UVICORN_PORT)
PORT=${PORT:-18000}
METRICS=$(cenv CF_METRICS_ADDR)
METRICS=${METRICS:-127.0.0.1:20241}
only_loopback() { # every TCP listener on port $1 is 127.0.0.1 / ::1
  # NOT a pipeline into grep -vq: grep -q exits at the first non-loopback listener, the
  # producer is then killed by SIGPIPE and pipefail makes the pipeline 141 -- which the
  # leading ! turns back into "yes, loopback only", i.e. the exposure this check exists to
  # catch would report a pass. Latent while ss fits the 64 KiB pipe buffer; wrong by design.
  local _l
  _l=$(ss -ltnH "( sport = :$1 )" 2>/dev/null | awk '{print $4}') || true
  ! grep -vqE '^(127\.0\.0\.1|\[::1\]):' <<<"$_l"
}
ready_conns() {
  curl -s -m 3 "http://$METRICS/ready" 2>/dev/null |
    python3 -c 'import json,sys
try: print(int(json.load(sys.stdin).get("readyConnections") or 0))
except Exception: print(0)'
}

chk "$UNIT active" "systemctl --user is-active --quiet $UNIT"
chk "$UNIT generated by Quadlet (not shadowed)" \
  "[[ \$(systemctl --user show -p FragmentPath --value $UNIT) == */systemd/generator/* ]]"
for _ in $(seq 1 20); do curl -fs -m 3 "http://127.0.0.1:$PORT/api/health" >/dev/null && break; sleep 3; done
chk "GUI /api/health on 127.0.0.1:$PORT" "curl -fs -m 3 http://127.0.0.1:$PORT/api/health >/dev/null"
chk "GUI port $PORT bound to loopback only" "only_loopback $PORT"
chk "HealthOnFailure=kill configured" \
  "[ \"\$(podman inspect -f '{{.Config.HealthcheckOnFailureAction}}' $CTR)\" = kill ]"

running=$(curl -fs -m 3 "http://127.0.0.1:$PORT/api/health" |
  python3 -c 'import json,sys; print(json.load(sys.stdin).get("process_running"))' 2>/dev/null)
if [[ $running == True ]]; then
  n=0
  for _ in $(seq 1 20); do
    n=$(ready_conns)
    ((n >= EXPECT_CONNS)) && break
    sleep 3
  done
  chk "cloudflared readyConnections=$n (want >= $EXPECT_CONNS)" "((${n:-0} >= EXPECT_CONNS))"
  chk "metrics port ${METRICS##*:} bound to loopback only" "only_loopback ${METRICS##*:}"
  argv_token=$(python3 - <<'PY'
import os
proc = os.environ.get("SMOKE_PROC", "/proc")
hits = 0
for pid in filter(str.isdigit, os.listdir(proc)):
    try:
        if open(f"{proc}/{pid}/comm").read().strip() != "cloudflared":
            continue
        args = open(f"{proc}/{pid}/cmdline", "rb").read().split(b"\0")
    except OSError:
        continue
    hits += any(a == b"--token" or a.startswith(b"--token=") for a in args)
print(hits)
PY
  )
  chk "tunnel token not in any cloudflared argv (--token-file only)" "[ '$argv_token' = 0 ]"
else
  echo "info  tunnel not running (unconfigured install?): edge checks skipped"
fi
# The first scheduled health check runs ~30s after a (re)start; allow up to 90s.
for _ in $(seq 1 18); do [ "$(podman inspect -f '{{.State.Health.Status}}' "$CTR" 2>/dev/null)" = healthy ] && break; sleep 5; done
chk "podman health status healthy" "[ \"\$(podman inspect -f '{{.State.Health.Status}}' $CTR)\" = healthy ]"

if [[ -e $QDIR/woow-cf-tunnel-auth.container ]]; then
  listen=$(sed -n 's/^AUTH_LISTEN=//p' "$ENV_FILE" 2>/dev/null)
  listen=${listen:-127.0.0.1:8888}
  host=${listen%:*}
  [[ $host == 0.0.0.0 ]] && host=127.0.0.1
  base=http://$host:${listen##*:}
  code() { curl -s -o /dev/null -w '%{http_code}' -m 3 "$@"; }
  for _ in $(seq 1 20); do [ "$(code "$base/healthz")" = 204 ] && break; sleep 3; done
  chk "auth proxy active" "systemctl --user is-active --quiet woow-cf-tunnel-auth.service"
  chk "auth proxy /healthz 204" "[ \"\$(code $base/healthz)\" = 204 ]"
  chk "auth proxy rejects anonymous requests (401)" "[ \"\$(code $base/api/config)\" = 401 ]"
  if [[ -n ${SMOKE_AUTH_USER:-} ]]; then
    # credentials go through a curl config on stdin, never argv
    login_code() {
      local u=$SMOKE_AUTH_USER:${SMOKE_AUTH_PASS:-}
      u=${u//\\/\\\\}
      u=${u//\"/\\\"}
      printf 'user = "%s"\n' "$u" | code -K - "$base/api/health"
    }
    # shellcheck disable=SC2016 # chk evals the string
    chk "auth proxy accepts the credentials (200)" '[ "$(login_code)" = 200 ]'
  fi
fi
if ((fails == 0)); then echo "smoke: all checks passed"; else echo "smoke: $fails check(s) failed"; exit 1; fi
